spring.application.name=daygo
server.port=8081
ors.api.key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjRiZDM0YjJkNDA5YTQyMzU4MjZhMjA2OWU2MTFhN2Q1IiwiaCI6Im11cm11cjY0In0=
mapbox.api.key=pk.eyJ1Ijoic3VwZXJmMWNpYWwiLCJhIjoiY211ajBicjdzMDAwbTJ3b213cXl0NTVxbyJ9.huWv0NEx-7EOvFz7dRTamg